# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'winch_gui.ui'
#
# Created: Mon Aug 25 12:29:38 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(966, 728)
        self.grid_main = QtGui.QWidget(MainWindow)
        self.grid_main.setObjectName(_fromUtf8("grid_main"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.grid_main)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.grid_lcd = QtGui.QGridLayout()
        self.grid_lcd.setObjectName(_fromUtf8("grid_lcd"))
        self.label_ta = QtGui.QLabel(self.grid_main)
        self.label_ta.setObjectName(_fromUtf8("label_ta"))
        self.grid_lcd.addWidget(self.label_ta, 0, 2, 1, 1)
        self.label_hur = QtGui.QLabel(self.grid_main)
        self.label_hur.setObjectName(_fromUtf8("label_hur"))
        self.grid_lcd.addWidget(self.label_hur, 0, 3, 1, 1)
        self.lcd_hur_3 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_hur_3.setFont(font)
        self.lcd_hur_3.setAutoFillBackground(True)
        self.lcd_hur_3.setFrameShape(QtGui.QFrame.Box)
        self.lcd_hur_3.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_hur_3.setLineWidth(2)
        self.lcd_hur_3.setMidLineWidth(0)
        self.lcd_hur_3.setSmallDecimalPoint(False)
        self.lcd_hur_3.setNumDigits(5)
        self.lcd_hur_3.setDigitCount(5)
        self.lcd_hur_3.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_hur_3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_hur_3.setProperty("value", 0.0)
        self.lcd_hur_3.setProperty("intValue", 0)
        self.lcd_hur_3.setObjectName(_fromUtf8("lcd_hur_3"))
        self.grid_lcd.addWidget(self.lcd_hur_3, 3, 3, 1, 1)
        self.lcd_vin_2 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_vin_2.setFont(font)
        self.lcd_vin_2.setAutoFillBackground(True)
        self.lcd_vin_2.setFrameShape(QtGui.QFrame.Box)
        self.lcd_vin_2.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_vin_2.setLineWidth(2)
        self.lcd_vin_2.setMidLineWidth(0)
        self.lcd_vin_2.setSmallDecimalPoint(False)
        self.lcd_vin_2.setNumDigits(5)
        self.lcd_vin_2.setDigitCount(5)
        self.lcd_vin_2.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_vin_2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_vin_2.setProperty("value", 0.0)
        self.lcd_vin_2.setProperty("intValue", 0)
        self.lcd_vin_2.setObjectName(_fromUtf8("lcd_vin_2"))
        self.grid_lcd.addWidget(self.lcd_vin_2, 2, 8, 1, 1)
        self.lcd_vin_4 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_vin_4.setFont(font)
        self.lcd_vin_4.setAutoFillBackground(True)
        self.lcd_vin_4.setFrameShape(QtGui.QFrame.Box)
        self.lcd_vin_4.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_vin_4.setLineWidth(2)
        self.lcd_vin_4.setMidLineWidth(0)
        self.lcd_vin_4.setSmallDecimalPoint(False)
        self.lcd_vin_4.setNumDigits(5)
        self.lcd_vin_4.setDigitCount(5)
        self.lcd_vin_4.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_vin_4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_vin_4.setProperty("value", 0.0)
        self.lcd_vin_4.setProperty("intValue", 0)
        self.lcd_vin_4.setObjectName(_fromUtf8("lcd_vin_4"))
        self.grid_lcd.addWidget(self.lcd_vin_4, 4, 8, 1, 1)
        self.lcd_alt_2 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_alt_2.setFont(font)
        self.lcd_alt_2.setAutoFillBackground(True)
        self.lcd_alt_2.setFrameShape(QtGui.QFrame.Box)
        self.lcd_alt_2.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_alt_2.setLineWidth(2)
        self.lcd_alt_2.setMidLineWidth(0)
        self.lcd_alt_2.setSmallDecimalPoint(False)
        self.lcd_alt_2.setNumDigits(5)
        self.lcd_alt_2.setDigitCount(5)
        self.lcd_alt_2.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_alt_2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_alt_2.setProperty("value", 0.0)
        self.lcd_alt_2.setProperty("intValue", 0)
        self.lcd_alt_2.setObjectName(_fromUtf8("lcd_alt_2"))
        self.grid_lcd.addWidget(self.lcd_alt_2, 2, 7, 1, 1)
        self.label_mc4 = QtGui.QLabel(self.grid_main)
        self.label_mc4.setObjectName(_fromUtf8("label_mc4"))
        self.grid_lcd.addWidget(self.label_mc4, 4, 0, 1, 1)
        self.label_ps = QtGui.QLabel(self.grid_main)
        self.label_ps.setObjectName(_fromUtf8("label_ps"))
        self.grid_lcd.addWidget(self.label_ps, 0, 4, 1, 1)
        self.label_wdir = QtGui.QLabel(self.grid_main)
        self.label_wdir.setObjectName(_fromUtf8("label_wdir"))
        self.grid_lcd.addWidget(self.label_wdir, 0, 6, 1, 1)
        self.lcd_alt_1 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_alt_1.setFont(font)
        self.lcd_alt_1.setAutoFillBackground(True)
        self.lcd_alt_1.setFrameShape(QtGui.QFrame.Box)
        self.lcd_alt_1.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_alt_1.setLineWidth(2)
        self.lcd_alt_1.setMidLineWidth(0)
        self.lcd_alt_1.setSmallDecimalPoint(False)
        self.lcd_alt_1.setNumDigits(5)
        self.lcd_alt_1.setDigitCount(5)
        self.lcd_alt_1.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_alt_1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_alt_1.setProperty("value", 0.0)
        self.lcd_alt_1.setProperty("intValue", 0)
        self.lcd_alt_1.setObjectName(_fromUtf8("lcd_alt_1"))
        self.grid_lcd.addWidget(self.lcd_alt_1, 1, 7, 1, 1)
        self.lcd_ta_2 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_ta_2.setFont(font)
        self.lcd_ta_2.setAutoFillBackground(True)
        self.lcd_ta_2.setFrameShape(QtGui.QFrame.Box)
        self.lcd_ta_2.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_ta_2.setLineWidth(2)
        self.lcd_ta_2.setMidLineWidth(0)
        self.lcd_ta_2.setSmallDecimalPoint(False)
        self.lcd_ta_2.setNumDigits(5)
        self.lcd_ta_2.setDigitCount(5)
        self.lcd_ta_2.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_ta_2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_ta_2.setProperty("value", 0.0)
        self.lcd_ta_2.setProperty("intValue", 0)
        self.lcd_ta_2.setObjectName(_fromUtf8("lcd_ta_2"))
        self.grid_lcd.addWidget(self.lcd_ta_2, 2, 2, 1, 1)
        self.lcd_ta_3 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_ta_3.setFont(font)
        self.lcd_ta_3.setAutoFillBackground(True)
        self.lcd_ta_3.setFrameShape(QtGui.QFrame.Box)
        self.lcd_ta_3.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_ta_3.setLineWidth(2)
        self.lcd_ta_3.setMidLineWidth(0)
        self.lcd_ta_3.setSmallDecimalPoint(False)
        self.lcd_ta_3.setNumDigits(5)
        self.lcd_ta_3.setDigitCount(5)
        self.lcd_ta_3.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_ta_3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_ta_3.setProperty("value", 0.0)
        self.lcd_ta_3.setProperty("intValue", 0)
        self.lcd_ta_3.setObjectName(_fromUtf8("lcd_ta_3"))
        self.grid_lcd.addWidget(self.lcd_ta_3, 3, 2, 1, 1)
        self.lcd_ta_1 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_ta_1.setFont(font)
        self.lcd_ta_1.setAutoFillBackground(True)
        self.lcd_ta_1.setFrameShape(QtGui.QFrame.Box)
        self.lcd_ta_1.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_ta_1.setLineWidth(2)
        self.lcd_ta_1.setMidLineWidth(0)
        self.lcd_ta_1.setSmallDecimalPoint(False)
        self.lcd_ta_1.setNumDigits(5)
        self.lcd_ta_1.setDigitCount(5)
        self.lcd_ta_1.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_ta_1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_ta_1.setProperty("value", 0.0)
        self.lcd_ta_1.setProperty("intValue", 0)
        self.lcd_ta_1.setObjectName(_fromUtf8("lcd_ta_1"))
        self.grid_lcd.addWidget(self.lcd_ta_1, 1, 2, 1, 1)
        self.lcd_ws_3 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_ws_3.setFont(font)
        self.lcd_ws_3.setAutoFillBackground(True)
        self.lcd_ws_3.setFrameShape(QtGui.QFrame.Box)
        self.lcd_ws_3.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_ws_3.setLineWidth(2)
        self.lcd_ws_3.setMidLineWidth(0)
        self.lcd_ws_3.setSmallDecimalPoint(False)
        self.lcd_ws_3.setNumDigits(5)
        self.lcd_ws_3.setDigitCount(5)
        self.lcd_ws_3.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_ws_3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_ws_3.setProperty("value", 0.0)
        self.lcd_ws_3.setProperty("intValue", 0)
        self.lcd_ws_3.setObjectName(_fromUtf8("lcd_ws_3"))
        self.grid_lcd.addWidget(self.lcd_ws_3, 3, 5, 1, 1)
        self.lcd_ws_2 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_ws_2.setFont(font)
        self.lcd_ws_2.setAutoFillBackground(True)
        self.lcd_ws_2.setFrameShape(QtGui.QFrame.Box)
        self.lcd_ws_2.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_ws_2.setLineWidth(2)
        self.lcd_ws_2.setMidLineWidth(0)
        self.lcd_ws_2.setSmallDecimalPoint(False)
        self.lcd_ws_2.setNumDigits(5)
        self.lcd_ws_2.setDigitCount(5)
        self.lcd_ws_2.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_ws_2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_ws_2.setProperty("value", 0.0)
        self.lcd_ws_2.setProperty("intValue", 0)
        self.lcd_ws_2.setObjectName(_fromUtf8("lcd_ws_2"))
        self.grid_lcd.addWidget(self.lcd_ws_2, 2, 5, 1, 1)
        self.lcd_ta_4 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_ta_4.setFont(font)
        self.lcd_ta_4.setAutoFillBackground(True)
        self.lcd_ta_4.setFrameShape(QtGui.QFrame.Box)
        self.lcd_ta_4.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_ta_4.setLineWidth(2)
        self.lcd_ta_4.setMidLineWidth(0)
        self.lcd_ta_4.setSmallDecimalPoint(False)
        self.lcd_ta_4.setNumDigits(5)
        self.lcd_ta_4.setDigitCount(5)
        self.lcd_ta_4.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_ta_4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_ta_4.setProperty("value", 0.0)
        self.lcd_ta_4.setProperty("intValue", 0)
        self.lcd_ta_4.setObjectName(_fromUtf8("lcd_ta_4"))
        self.grid_lcd.addWidget(self.lcd_ta_4, 4, 2, 1, 1)
        self.lcd_wdir_3 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_wdir_3.setFont(font)
        self.lcd_wdir_3.setAutoFillBackground(True)
        self.lcd_wdir_3.setFrameShape(QtGui.QFrame.Box)
        self.lcd_wdir_3.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_wdir_3.setLineWidth(2)
        self.lcd_wdir_3.setMidLineWidth(0)
        self.lcd_wdir_3.setSmallDecimalPoint(False)
        self.lcd_wdir_3.setNumDigits(5)
        self.lcd_wdir_3.setDigitCount(5)
        self.lcd_wdir_3.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_wdir_3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_wdir_3.setProperty("value", 0.0)
        self.lcd_wdir_3.setProperty("intValue", 0)
        self.lcd_wdir_3.setObjectName(_fromUtf8("lcd_wdir_3"))
        self.grid_lcd.addWidget(self.lcd_wdir_3, 3, 6, 1, 1)
        self.lcd_ws_1 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_ws_1.setFont(font)
        self.lcd_ws_1.setAutoFillBackground(True)
        self.lcd_ws_1.setFrameShape(QtGui.QFrame.Box)
        self.lcd_ws_1.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_ws_1.setLineWidth(2)
        self.lcd_ws_1.setMidLineWidth(0)
        self.lcd_ws_1.setSmallDecimalPoint(False)
        self.lcd_ws_1.setNumDigits(5)
        self.lcd_ws_1.setDigitCount(5)
        self.lcd_ws_1.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_ws_1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_ws_1.setProperty("value", 0.0)
        self.lcd_ws_1.setProperty("intValue", 0)
        self.lcd_ws_1.setObjectName(_fromUtf8("lcd_ws_1"))
        self.grid_lcd.addWidget(self.lcd_ws_1, 1, 5, 1, 1)
        self.label_mc2 = QtGui.QLabel(self.grid_main)
        self.label_mc2.setObjectName(_fromUtf8("label_mc2"))
        self.grid_lcd.addWidget(self.label_mc2, 2, 0, 1, 1)
        self.lcd_alt_4 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_alt_4.setFont(font)
        self.lcd_alt_4.setAutoFillBackground(True)
        self.lcd_alt_4.setFrameShape(QtGui.QFrame.Box)
        self.lcd_alt_4.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_alt_4.setLineWidth(2)
        self.lcd_alt_4.setMidLineWidth(0)
        self.lcd_alt_4.setSmallDecimalPoint(False)
        self.lcd_alt_4.setNumDigits(5)
        self.lcd_alt_4.setDigitCount(5)
        self.lcd_alt_4.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_alt_4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_alt_4.setProperty("value", 0.0)
        self.lcd_alt_4.setProperty("intValue", 0)
        self.lcd_alt_4.setObjectName(_fromUtf8("lcd_alt_4"))
        self.grid_lcd.addWidget(self.lcd_alt_4, 4, 7, 1, 1)
        self.lcd_alt_3 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_alt_3.setFont(font)
        self.lcd_alt_3.setAutoFillBackground(True)
        self.lcd_alt_3.setFrameShape(QtGui.QFrame.Box)
        self.lcd_alt_3.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_alt_3.setLineWidth(2)
        self.lcd_alt_3.setMidLineWidth(0)
        self.lcd_alt_3.setSmallDecimalPoint(False)
        self.lcd_alt_3.setNumDigits(5)
        self.lcd_alt_3.setDigitCount(5)
        self.lcd_alt_3.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_alt_3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_alt_3.setProperty("value", 0.0)
        self.lcd_alt_3.setProperty("intValue", 0)
        self.lcd_alt_3.setObjectName(_fromUtf8("lcd_alt_3"))
        self.grid_lcd.addWidget(self.lcd_alt_3, 3, 7, 1, 1)
        self.label_mc3 = QtGui.QLabel(self.grid_main)
        self.label_mc3.setObjectName(_fromUtf8("label_mc3"))
        self.grid_lcd.addWidget(self.label_mc3, 3, 0, 1, 1)
        self.label_alt = QtGui.QLabel(self.grid_main)
        self.label_alt.setObjectName(_fromUtf8("label_alt"))
        self.grid_lcd.addWidget(self.label_alt, 0, 7, 1, 1)
        self.label_vin = QtGui.QLabel(self.grid_main)
        self.label_vin.setObjectName(_fromUtf8("label_vin"))
        self.grid_lcd.addWidget(self.label_vin, 0, 8, 1, 1)
        self.label_ws = QtGui.QLabel(self.grid_main)
        self.label_ws.setObjectName(_fromUtf8("label_ws"))
        self.grid_lcd.addWidget(self.label_ws, 0, 5, 1, 1)
        self.lcd_vin_1 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_vin_1.setFont(font)
        self.lcd_vin_1.setAutoFillBackground(True)
        self.lcd_vin_1.setFrameShape(QtGui.QFrame.Box)
        self.lcd_vin_1.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_vin_1.setLineWidth(2)
        self.lcd_vin_1.setMidLineWidth(0)
        self.lcd_vin_1.setSmallDecimalPoint(False)
        self.lcd_vin_1.setNumDigits(5)
        self.lcd_vin_1.setDigitCount(5)
        self.lcd_vin_1.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_vin_1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_vin_1.setProperty("value", 0.0)
        self.lcd_vin_1.setProperty("intValue", 0)
        self.lcd_vin_1.setObjectName(_fromUtf8("lcd_vin_1"))
        self.grid_lcd.addWidget(self.lcd_vin_1, 1, 8, 1, 1)
        self.lcd_ps_4 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_ps_4.setFont(font)
        self.lcd_ps_4.setAutoFillBackground(True)
        self.lcd_ps_4.setFrameShape(QtGui.QFrame.Box)
        self.lcd_ps_4.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_ps_4.setLineWidth(2)
        self.lcd_ps_4.setMidLineWidth(0)
        self.lcd_ps_4.setSmallDecimalPoint(False)
        self.lcd_ps_4.setNumDigits(5)
        self.lcd_ps_4.setDigitCount(5)
        self.lcd_ps_4.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_ps_4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_ps_4.setProperty("value", 0.0)
        self.lcd_ps_4.setProperty("intValue", 0)
        self.lcd_ps_4.setObjectName(_fromUtf8("lcd_ps_4"))
        self.grid_lcd.addWidget(self.lcd_ps_4, 4, 4, 1, 1)
        self.lcd_wdir_4 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_wdir_4.setFont(font)
        self.lcd_wdir_4.setAutoFillBackground(True)
        self.lcd_wdir_4.setFrameShape(QtGui.QFrame.Box)
        self.lcd_wdir_4.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_wdir_4.setLineWidth(2)
        self.lcd_wdir_4.setMidLineWidth(0)
        self.lcd_wdir_4.setSmallDecimalPoint(False)
        self.lcd_wdir_4.setNumDigits(5)
        self.lcd_wdir_4.setDigitCount(5)
        self.lcd_wdir_4.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_wdir_4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_wdir_4.setProperty("value", 0.0)
        self.lcd_wdir_4.setProperty("intValue", 0)
        self.lcd_wdir_4.setObjectName(_fromUtf8("lcd_wdir_4"))
        self.grid_lcd.addWidget(self.lcd_wdir_4, 4, 6, 1, 1)
        self.lcd_ws_4 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_ws_4.setFont(font)
        self.lcd_ws_4.setAutoFillBackground(True)
        self.lcd_ws_4.setFrameShape(QtGui.QFrame.Box)
        self.lcd_ws_4.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_ws_4.setLineWidth(2)
        self.lcd_ws_4.setMidLineWidth(0)
        self.lcd_ws_4.setSmallDecimalPoint(False)
        self.lcd_ws_4.setNumDigits(6)
        self.lcd_ws_4.setDigitCount(6)
        self.lcd_ws_4.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_ws_4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_ws_4.setProperty("value", 0.0)
        self.lcd_ws_4.setProperty("intValue", 0)
        self.lcd_ws_4.setObjectName(_fromUtf8("lcd_ws_4"))
        self.grid_lcd.addWidget(self.lcd_ws_4, 4, 5, 1, 1)
        self.label_mc1 = QtGui.QLabel(self.grid_main)
        self.label_mc1.setObjectName(_fromUtf8("label_mc1"))
        self.grid_lcd.addWidget(self.label_mc1, 1, 0, 1, 1)
        self.lcd_hur_1 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_hur_1.setFont(font)
        self.lcd_hur_1.setAutoFillBackground(True)
        self.lcd_hur_1.setFrameShape(QtGui.QFrame.Box)
        self.lcd_hur_1.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_hur_1.setLineWidth(2)
        self.lcd_hur_1.setMidLineWidth(0)
        self.lcd_hur_1.setSmallDecimalPoint(False)
        self.lcd_hur_1.setNumDigits(5)
        self.lcd_hur_1.setDigitCount(5)
        self.lcd_hur_1.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_hur_1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_hur_1.setProperty("value", 0.0)
        self.lcd_hur_1.setProperty("intValue", 0)
        self.lcd_hur_1.setObjectName(_fromUtf8("lcd_hur_1"))
        self.grid_lcd.addWidget(self.lcd_hur_1, 1, 3, 1, 1)
        self.lcd_ps_1 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_ps_1.setFont(font)
        self.lcd_ps_1.setAutoFillBackground(True)
        self.lcd_ps_1.setFrameShape(QtGui.QFrame.Box)
        self.lcd_ps_1.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_ps_1.setLineWidth(2)
        self.lcd_ps_1.setMidLineWidth(0)
        self.lcd_ps_1.setSmallDecimalPoint(False)
        self.lcd_ps_1.setNumDigits(5)
        self.lcd_ps_1.setDigitCount(5)
        self.lcd_ps_1.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_ps_1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_ps_1.setProperty("value", 0.0)
        self.lcd_ps_1.setProperty("intValue", 0)
        self.lcd_ps_1.setObjectName(_fromUtf8("lcd_ps_1"))
        self.grid_lcd.addWidget(self.lcd_ps_1, 1, 4, 1, 1)
        self.lcd_vin_3 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_vin_3.setFont(font)
        self.lcd_vin_3.setAutoFillBackground(True)
        self.lcd_vin_3.setFrameShape(QtGui.QFrame.Box)
        self.lcd_vin_3.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_vin_3.setLineWidth(2)
        self.lcd_vin_3.setMidLineWidth(0)
        self.lcd_vin_3.setSmallDecimalPoint(False)
        self.lcd_vin_3.setNumDigits(5)
        self.lcd_vin_3.setDigitCount(5)
        self.lcd_vin_3.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_vin_3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_vin_3.setProperty("value", 0.0)
        self.lcd_vin_3.setProperty("intValue", 0)
        self.lcd_vin_3.setObjectName(_fromUtf8("lcd_vin_3"))
        self.grid_lcd.addWidget(self.lcd_vin_3, 3, 8, 1, 1)
        self.lcd_ps_3 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_ps_3.setFont(font)
        self.lcd_ps_3.setAutoFillBackground(True)
        self.lcd_ps_3.setFrameShape(QtGui.QFrame.Box)
        self.lcd_ps_3.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_ps_3.setLineWidth(2)
        self.lcd_ps_3.setMidLineWidth(0)
        self.lcd_ps_3.setSmallDecimalPoint(False)
        self.lcd_ps_3.setNumDigits(5)
        self.lcd_ps_3.setDigitCount(5)
        self.lcd_ps_3.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_ps_3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_ps_3.setProperty("value", 0.0)
        self.lcd_ps_3.setProperty("intValue", 0)
        self.lcd_ps_3.setObjectName(_fromUtf8("lcd_ps_3"))
        self.grid_lcd.addWidget(self.lcd_ps_3, 3, 4, 1, 1)
        self.lcd_wdir_2 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_wdir_2.setFont(font)
        self.lcd_wdir_2.setAutoFillBackground(True)
        self.lcd_wdir_2.setFrameShape(QtGui.QFrame.Box)
        self.lcd_wdir_2.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_wdir_2.setLineWidth(2)
        self.lcd_wdir_2.setMidLineWidth(0)
        self.lcd_wdir_2.setSmallDecimalPoint(False)
        self.lcd_wdir_2.setNumDigits(5)
        self.lcd_wdir_2.setDigitCount(5)
        self.lcd_wdir_2.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_wdir_2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_wdir_2.setProperty("value", 0.0)
        self.lcd_wdir_2.setProperty("intValue", 0)
        self.lcd_wdir_2.setObjectName(_fromUtf8("lcd_wdir_2"))
        self.grid_lcd.addWidget(self.lcd_wdir_2, 2, 6, 1, 1)
        self.lcd_wdir_1 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_wdir_1.setFont(font)
        self.lcd_wdir_1.setAutoFillBackground(True)
        self.lcd_wdir_1.setFrameShape(QtGui.QFrame.Box)
        self.lcd_wdir_1.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_wdir_1.setLineWidth(2)
        self.lcd_wdir_1.setMidLineWidth(0)
        self.lcd_wdir_1.setSmallDecimalPoint(False)
        self.lcd_wdir_1.setNumDigits(5)
        self.lcd_wdir_1.setDigitCount(5)
        self.lcd_wdir_1.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_wdir_1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_wdir_1.setProperty("value", 0.0)
        self.lcd_wdir_1.setProperty("intValue", 0)
        self.lcd_wdir_1.setObjectName(_fromUtf8("lcd_wdir_1"))
        self.grid_lcd.addWidget(self.lcd_wdir_1, 1, 6, 1, 1)
        self.lcd_hur_2 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_hur_2.setFont(font)
        self.lcd_hur_2.setAutoFillBackground(True)
        self.lcd_hur_2.setFrameShape(QtGui.QFrame.Box)
        self.lcd_hur_2.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_hur_2.setLineWidth(2)
        self.lcd_hur_2.setMidLineWidth(0)
        self.lcd_hur_2.setSmallDecimalPoint(False)
        self.lcd_hur_2.setNumDigits(5)
        self.lcd_hur_2.setDigitCount(5)
        self.lcd_hur_2.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_hur_2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_hur_2.setProperty("value", 0.0)
        self.lcd_hur_2.setProperty("intValue", 0)
        self.lcd_hur_2.setObjectName(_fromUtf8("lcd_hur_2"))
        self.grid_lcd.addWidget(self.lcd_hur_2, 2, 3, 1, 1)
        self.lcd_hur_4 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_hur_4.setFont(font)
        self.lcd_hur_4.setAutoFillBackground(True)
        self.lcd_hur_4.setFrameShape(QtGui.QFrame.Box)
        self.lcd_hur_4.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_hur_4.setLineWidth(2)
        self.lcd_hur_4.setMidLineWidth(0)
        self.lcd_hur_4.setSmallDecimalPoint(False)
        self.lcd_hur_4.setNumDigits(5)
        self.lcd_hur_4.setDigitCount(5)
        self.lcd_hur_4.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_hur_4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_hur_4.setProperty("value", 0.0)
        self.lcd_hur_4.setProperty("intValue", 0)
        self.lcd_hur_4.setObjectName(_fromUtf8("lcd_hur_4"))
        self.grid_lcd.addWidget(self.lcd_hur_4, 4, 3, 1, 1)
        self.lcd_ps_2 = QtGui.QLCDNumber(self.grid_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lcd_ps_2.setFont(font)
        self.lcd_ps_2.setAutoFillBackground(True)
        self.lcd_ps_2.setFrameShape(QtGui.QFrame.Box)
        self.lcd_ps_2.setFrameShadow(QtGui.QFrame.Plain)
        self.lcd_ps_2.setLineWidth(2)
        self.lcd_ps_2.setMidLineWidth(0)
        self.lcd_ps_2.setSmallDecimalPoint(False)
        self.lcd_ps_2.setNumDigits(5)
        self.lcd_ps_2.setDigitCount(5)
        self.lcd_ps_2.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_ps_2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_ps_2.setProperty("value", 0.0)
        self.lcd_ps_2.setProperty("intValue", 0)
        self.lcd_ps_2.setObjectName(_fromUtf8("lcd_ps_2"))
        self.grid_lcd.addWidget(self.lcd_ps_2, 2, 4, 1, 1)
        self.radio_ref_4 = QtGui.QRadioButton(self.grid_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_ref_4.sizePolicy().hasHeightForWidth())
        self.radio_ref_4.setSizePolicy(sizePolicy)
        self.radio_ref_4.setMaximumSize(QtCore.QSize(20, 20))
        self.radio_ref_4.setAutoFillBackground(False)
        self.radio_ref_4.setText(_fromUtf8(""))
        self.radio_ref_4.setChecked(True)
        self.radio_ref_4.setObjectName(_fromUtf8("radio_ref_4"))
        self.grid_lcd.addWidget(self.radio_ref_4, 4, 1, 1, 1)
        self.radio_ref_2 = QtGui.QRadioButton(self.grid_main)
        self.radio_ref_2.setText(_fromUtf8(""))
        self.radio_ref_2.setObjectName(_fromUtf8("radio_ref_2"))
        self.grid_lcd.addWidget(self.radio_ref_2, 2, 1, 1, 1)
        self.radio_ref_3 = QtGui.QRadioButton(self.grid_main)
        self.radio_ref_3.setText(_fromUtf8(""))
        self.radio_ref_3.setObjectName(_fromUtf8("radio_ref_3"))
        self.grid_lcd.addWidget(self.radio_ref_3, 3, 1, 1, 1)
        self.radio_ref_1 = QtGui.QRadioButton(self.grid_main)
        self.radio_ref_1.setText(_fromUtf8(""))
        self.radio_ref_1.setObjectName(_fromUtf8("radio_ref_1"))
        self.grid_lcd.addWidget(self.radio_ref_1, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.grid_main)
        self.label.setObjectName(_fromUtf8("label"))
        self.grid_lcd.addWidget(self.label, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.grid_lcd)
        self.mpl = MplWidget(self.grid_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl.sizePolicy().hasHeightForWidth())
        self.mpl.setSizePolicy(sizePolicy)
        self.mpl.setObjectName(_fromUtf8("mpl"))
        self.verticalLayout_2.addWidget(self.mpl)
        self.grid_adjust = QtGui.QGridLayout()
        self.grid_adjust.setObjectName(_fromUtf8("grid_adjust"))
        self.recordButton = QtGui.QPushButton(self.grid_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recordButton.sizePolicy().hasHeightForWidth())
        self.recordButton.setSizePolicy(sizePolicy)
        self.recordButton.setObjectName(_fromUtf8("recordButton"))
        self.grid_adjust.addWidget(self.recordButton, 1, 6, 1, 1)
        self.analyseButton = QtGui.QPushButton(self.grid_main)
        self.analyseButton.setObjectName(_fromUtf8("analyseButton"))
        self.grid_adjust.addWidget(self.analyseButton, 1, 5, 1, 1)
        self.filelineEdit = QtGui.QLineEdit(self.grid_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filelineEdit.sizePolicy().hasHeightForWidth())
        self.filelineEdit.setSizePolicy(sizePolicy)
        self.filelineEdit.setText(_fromUtf8(""))
        self.filelineEdit.setObjectName(_fromUtf8("filelineEdit"))
        self.grid_adjust.addWidget(self.filelineEdit, 1, 3, 1, 1)
        self.COMlineEdit = QtGui.QLineEdit(self.grid_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.COMlineEdit.sizePolicy().hasHeightForWidth())
        self.COMlineEdit.setSizePolicy(sizePolicy)
        self.COMlineEdit.setObjectName(_fromUtf8("COMlineEdit"))
        self.grid_adjust.addWidget(self.COMlineEdit, 0, 3, 1, 1)
        self.comboBox = QtGui.QComboBox(self.grid_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 20))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.grid_adjust.addWidget(self.comboBox, 1, 0, 1, 1)
        self.COMPort = QtGui.QLabel(self.grid_main)
        self.COMPort.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.COMPort.setObjectName(_fromUtf8("COMPort"))
        self.grid_adjust.addWidget(self.COMPort, 0, 2, 1, 1)
        self.File = QtGui.QLabel(self.grid_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.File.sizePolicy().hasHeightForWidth())
        self.File.setSizePolicy(sizePolicy)
        self.File.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.File.setObjectName(_fromUtf8("File"))
        self.grid_adjust.addWidget(self.File, 1, 2, 1, 1)
        self.monitorButton = QtGui.QPushButton(self.grid_main)
        self.monitorButton.setObjectName(_fromUtf8("monitorButton"))
        self.grid_adjust.addWidget(self.monitorButton, 0, 0, 1, 1)
        self.kled = KLed(self.grid_main)
        self.kled.setEnabled(False)
        self.kled.setState(KLed.On)
        self.kled.setShape(KLed.Rectangular)
        self.kled.setColor(QtGui.QColor(195, 195, 195))
        self.kled.setObjectName(_fromUtf8("kled"))
        self.grid_adjust.addWidget(self.kled, 0, 6, 1, 1)
        self.yaxischeckBox = QtGui.QCheckBox(self.grid_main)
        self.yaxischeckBox.setEnabled(True)
        self.yaxischeckBox.setChecked(True)
        self.yaxischeckBox.setObjectName(_fromUtf8("yaxischeckBox"))
        self.grid_adjust.addWidget(self.yaxischeckBox, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.grid_adjust)
        MainWindow.setCentralWidget(self.grid_main)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 966, 21))
        self.menuBar.setMouseTracking(True)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuConfigure = QtGui.QMenu(self.menuBar)
        self.menuConfigure.setObjectName(_fromUtf8("menuConfigure"))
        MainWindow.setMenuBar(self.menuBar)
        self.mplactionOpen = QtGui.QAction(MainWindow)
        self.mplactionOpen.setObjectName(_fromUtf8("mplactionOpen"))
        self.seperator = QtGui.QAction(MainWindow)
        self.seperator.setObjectName(_fromUtf8("seperator"))
        self.mplactionQuit = QtGui.QAction(MainWindow)
        self.mplactionQuit.setObjectName(_fromUtf8("mplactionQuit"))
        self.actionJob = QtGui.QAction(MainWindow)
        self.actionJob.setObjectName(_fromUtf8("actionJob"))
        self.openCom = QtGui.QAction(MainWindow)
        self.openCom.setObjectName(_fromUtf8("openCom"))
        self.filePath = QtGui.QAction(MainWindow)
        self.filePath.setObjectName(_fromUtf8("filePath"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuConfigure.addAction(self.openCom)
        self.menuConfigure.addAction(self.filePath)
        self.menuConfigure.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuConfigure.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_ta.setText(_translate("MainWindow", "Temperatur", None))
        self.label_hur.setText(_translate("MainWindow", "relative Humidity", None))
        self.label_mc4.setText(_translate("MainWindow", "Sensor Unit 4", None))
        self.label_ps.setText(_translate("MainWindow", "Pressure", None))
        self.label_wdir.setText(_translate("MainWindow", "Wind Direction", None))
        self.label_mc2.setText(_translate("MainWindow", "Sensor Unit 2", None))
        self.label_mc3.setText(_translate("MainWindow", "Sensor Unit 3", None))
        self.label_alt.setText(_translate("MainWindow", "Hight", None))
        self.label_vin.setText(_translate("MainWindow", "Batterie", None))
        self.label_ws.setText(_translate("MainWindow", "Wind Speed", None))
        self.label_mc1.setText(_translate("MainWindow", "Sensor Unit 1", None))
        self.label.setText(_translate("MainWindow", "ref.", None))
        self.recordButton.setText(_translate("MainWindow", "Start record", None))
        self.analyseButton.setText(_translate("MainWindow", "analyse", None))
        self.COMlineEdit.setText(_translate("MainWindow", "/dev/ttyUSB0", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Temperature", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Relative Hum", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "Wind Speed", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "Wind Direction", None))
        self.COMPort.setText(_translate("MainWindow", "COM Port", None))
        self.File.setText(_translate("MainWindow", "File", None))
        self.monitorButton.setText(_translate("MainWindow", "update Monitor", None))
        self.yaxischeckBox.setText(_translate("MainWindow", "Y Axis = Hight ", None))
        self.menuConfigure.setTitle(_translate("MainWindow", "configure", None))
        self.mplactionOpen.setText(_translate("MainWindow", "file", None))
        self.seperator.setText(_translate("MainWindow", "seperate", None))
        self.mplactionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionJob.setText(_translate("MainWindow", "Job", None))
        self.openCom.setText(_translate("MainWindow", "Com Port", None))
        self.filePath.setText(_translate("MainWindow", "File", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))

from mplwidget import MplWidget
from PyKDE4.kdeui import KLed
#from kled import KLed
